import Head from "next/head";
import Image from "next/image";
export default function Home() {
  return (
    <>
      <Head>
        <title>Nightbridge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center text-white fw-bold" aria-label="Alternative rock band based in Scotland"><div style={{ marginBottom: "17rem"}} aria-hidden="true">ALTERNATIVE ROCK<br />BAND</div><div aria-hidden="true">BASED IN<br />SCOTLAND</div></h1>
      </main>
    </>
  );
}
