import Head from "next/head";
import Hero from "../comps/Hero";
import Externals from "../comps/Externals";
import Upcoming from "../comps/Upcoming";
export default function Home() {
  return (
    <>
      <Head>
        <title>Nightbridge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <h1 className="d-block d-lg-none display-6 text-center mb-5 title-three">ALTERNATIVE ROCK BAND BASED IN SCOTLAND</h1>
        <Externals />
        <Upcoming />
      </main>
    </>
  );
}
